= Provengo online course
// :rootpath: ./
:idprefix:
:idseparator: -
:!example-caption:
:!table-caption:
:page-pagination:
:page-layout: tiles
:description: An online course for the Provengo test automation tools.
:keywords: Provengo, Behavioral Programming, Test Automation

This course is a collection of video clips and exercise for learning the Provengo test automation tool. It is intended for people who are new to Provengo and want to learn how to use it.

NOTE: Please visit https://docs.provengo.tech[provengo.tech] for the full documentation of the tool.



[cols="1,3"]
|===
| Lesson | Topics (click to view)

| 1) A short introduction to Provengo and the course.
| 
xref:tutorials/welcome.adoc[Welcome to Provengo] 
★ xref:tutorials/overview.adoc[Course overview]

| 2) Installing Provengo and using the command line interface.
| 
xref:tutorials/installation.adoc[Provengo installation]
★ xref:tutorials/command-structure.adoc[Command structure]
★ xref:tutorials/provengo-docs.adoc[Provengo documentation]

| 3) Writing a test model and executing it.
| 
xref:tutorials/prestashop.adoc[The PrestaShop SUT]
★ xref:tutorials/writing-your-first-model.adoc[Writing your first model]
★ xref:tutorials/adding-an-interleaved-story.adoc[Interleaving]
★ xref:tutorials/refining-the-model.adoc[Model refinement]
★ xref:tutorials/event-sets.adoc[Event sets]

| 4) Interacting with web applications and generating optimized test suites.
| 
xref:tutorials/selenium.adoc[Using Selenium]
★ xref:tutorials/step-files.adoc[Working with step files]
★ xref:tutorials/execution.adoc[Creating & executing test suites]
★ xref:tutorials/ranking.adoc[Ranking & prioritization]
|===