name: Publish to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    # - name: Install Antora
    #   run: npm i antora
    - name: Prepare Antora
      run: npm i @antora/cli@3.1.2
      run: npm i @antora/site-generator@3.1.2
      run: npm i asciidoctor-kroki
      run: npm i @djencks/asciidoctor-mathjax
    - name: Generate Site
      run:  npx antora docs/antora/antora-playbook.yml
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/site